### ISSUE TITLE
Couldn't find the module

### ISSUE THREAD

**Issue by deckameron** [mpociot/TiCollectionView#10]
Hi mpociot,

I am trying to use your module on an iphone app but I get this error.
I am using Titanium build: 3.4.1.201410281727 and SDK 3.4.1.

Thank you!

**Comment by mpociot** [comment]
Could you please provide a more detailed error description? 
How did you install the module?

Take a look at: http://gitt.io/component/de.marcelpociot.collectionview

**Comment by deckameron** [comment]
I installed it by unziping the dist file into my "modules/iphone" folder of my project. 
I did it just like with the other modules I work with.

**Comment by mpociot** [comment]
Could you please provide a log file?

**Comment by ak0815** [comment]
Hello,

i have the same Problem. iOS:

[DEBUG] :  Reading stylesheet from: /Users/andreaskopf/Library/Developer/CoreSimulator/Devices/65A9925A-3C77-4F2A-BF08-BFCEAF93C33C/data/Containers/Bundle/Application/DDDD8D8B-4BBE-425F-89AA-4C51DD88485F/TEST APP.app/stylesheet.plist
[DEBUG] :  2015-01-13 20:48:26.702 TEST APP[34093:910199] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
[INFO] :   TEST APP/0.0.2.2.2 (3.4.1.5982e8f)
[DEBUG] :  2015-01-13 20:48:26.703 TEST APP[34093:910199] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
[DEBUG] :  Loading: /Users/andreaskopf/Library/Developer/CoreSimulator/Devices/65A9925A-3C77-4F2A-BF08-BFCEAF93C33C/data/Containers/Bundle/Application/DDDD8D8B-4BBE-425F-89AA-4C51DD88485F/TEST APP.app/app.js, Resource: app_js
[INFO] :   [object DeMarcelpociotCollectionviewModule] loaded
[DEBUG] :  Loading: /Users/andreaskopf/Library/Developer/CoreSimulator/Devices/65A9925A-3C77-4F2A-BF08-BFCEAF93C33C/data/Containers/Bundle/Application/DDDD8D8B-4BBE-425F-89AA-4C51DD88485F/TEST APP.app/de.marcelpociot.collectionview.js, Resource: de_marcelpociot_collectionview_js
[DEBUG] :  Loading: /Users/andreaskopf/Library/Developer/CoreSimulator/Devices/65A9925A-3C77-4F2A-BF08-BFCEAF93C33C/data/Containers/Bundle/Application/DDDD8D8B-4BBE-425F-89AA-4C51DD88485F/TEST APP.app/CollectionView.js, Resource: CollectionView_js
[ERROR] :  Script Error Couldn't find module: CollectionView
[DEBUG] :  Application booted in 97.488999 ms

BG
Andy

**Comment by ak0815** [comment]
It works:

wrong:
var listView = require("CollectionView")".createCollectionView({

right:
var listView = collectionView.createCollectionView({

**Comment by mpociot** [comment]
@ak0815 this only works on iOS.
To support iOS and Android you need to use the CommonJS file, provided in the "lib" folder , and include it in your Titanium project.

See: https://github.com/mpociot/TiCollectionView/blob/master/lib/CollectionView.js

I think the documentation needs to clarifies this a bit more.

**Comment by ak0815** [comment]
Thanks. Now it works :-)

One Question:

How do I enable Waterfall? To:

 layout:'LAYOUT_WATERFALL',
    columnCount:3,
    minimumColumnSpacing:10,
    minimumInteritemSpacing:5,
    renderDirection:'DIRECTION_SHORTEST_FIRST'

BG 
Andy

**Comment by mpociot** [comment]
These properties are module constants.

Apply them like this:

```javascript
var collectionView = require("de.marcelpociot.collectionview");

var listView = collectionView.createCollectionView({
    layout: collectionView.LAYOUT_WATERFALL,
    columnCount: 3,
    minimumColumnSpacing: 20,
    minimumInteritemSpacing: 50,
    renderDirection: collectionView.DIRECTION_LEFT_TO_RIGHT,
    // Other properties...
});
```

**Comment by ak0815** [comment]
Thank you very much

**Comment by deckameron** [comment]
Thank you very much @mpociot  and @ak0815 !
With your explanation I was able to get it working.
