### ISSUE TITLE
Calendar Layout 

### ISSUE THREAD

**Issue by mpociot** [mpociot/TiCollectionView#11]
It'd be cool to have a calendar layout:

https://github.com/erichoracek/MSCollectionViewCalendarLayout

If anyone knows of a similar thing for android (that uses the gridview), let me know!

**Comment by nicka** [comment]
That would be really awesome!

**Comment by FokkeZB** [comment]
I have an (client) app that has a similar calendar layout but then horizontally. It currently uses a giant ScrollView with some rendering tricks. Would be nice to have that as a layout option as well:

![ios simulator screen shot 13 jan 2015 09 51 16](https://cloud.githubusercontent.com/assets/2699409/5718071/de4ef21e-9b09-11e4-82bb-971d1e9c3076.png)

**Comment by yuchi** [comment]
@FokkeZB great screen dude!

**Comment by mpociot** [comment]
@FokkeZB hm..don't know if the layout can be implemented in such a flexible way, as this is a very special use case

**Comment by yozef** [comment]
Another option... is this one https://github.com/leverdeterre/CalendarIOS7

**Comment by mpociot** [comment]
I think the whole calendar thing might become too complex for the CollectionView module. Maybe it would make more sense to make a custom module out of it.

**Comment by FokkeZB** [comment]
+1 for (draggable) cross platform calendar module
