### ISSUE TITLE
Dynamic loading

### ISSUE THREAD

**Issue by deckameron** [mpociot/TiCollectionView#14]
Is it possible to use a event listener for the scroll event in order to use dynamic loading?
I tried to use it like this:

listView.addEventListener('scroll', function(){
    Titanium.API.info('scrolling...');
});

The event never gets fired.
Am I doing anything wrong?
Thank you!

**Comment by darknos** [comment]
with listview you can use setMarker({sectionIndex:5, itemIndex:10}); and "marker" event, but I'm not sure that it will work with TiCollectionView

lets ask author :)

**Comment by mpociot** [comment]
No, the "marker" event isn't implemented yet.

**Comment by ak0815** [comment]
@mpociot Kannst du das Scroll Event vielleicht hinzufügen? Das wäre echt Klasse.

**Comment by mpociot** [comment]
So I took a look at it again.
I was wrong , the "marker" event is implemented :)

Use it, as you would with a regular listView.

```javascript
collectionView.addEventListener("marker", function(e){
    // Load more entries and set a new marker...
});
collectionView.setMarker({sectionIndex:0,itemIndex: 10 });
```
