### ISSUE TITLE
[ERROR] :  Script Error Couldn't find module: CollectionView for architecture: x86_64

### ISSUE THREAD

**Issue by abada** [mpociot/TiCollectionView#20]
Ti SDK : 3.5.0

TiCollectionView version 1.2.0 (latest version)

I tried to install this module from gitt.io but give me 

[INFO]  de.marcelpociot.collectionview searching...
[ERROR] de.marcelpociot.collectionview:commonjs no distributable available
[ERROR] de.marcelpociot.collectionview:android no distributable available
[ERROR] de.marcelpociot.collectionview:ios no distributable available

when i installed it (Manual Method for ios and android ) from Repository  (after download it)

 <module platform="android">de.marcelpociot.collectionview</module>
        <module platform="iphone">de.marcelpociot.collectionview</module>

and wrote the example code from README.md

and after run the app 

console show this error

[ERROR] :  Script Error Couldn't find module: CollectionView for architecture: x86_64

**Comment by mpociot** [comment]
Hi,

please download the "CollectionView" commonJS module from: https://github.com/mpociot/TiCollectionView/tree/master/lib and place it in your "lib" directory.

**Comment by yuchi** [comment]
@mpociot, why aren’t you using [this method](http://docs.appcelerator.com/titanium/latest/#!/guide/Titanium_Module_Concepts-section-35621751_TitaniumModuleConcepts-PackagedJavaScriptandHybridModules) to package your js file directly in the module? What’s stopping you? Did you tested it and it‘s not working?

**Comment by yuchi** [comment]
It says:

> #### Packaged JavaScript and Hybrid Modules
>
> To package JavaScript as a native module, create a JavaScript module named `<module-id>.js` in the module's `assets` folder. The APIs exported by this module form the API of the packaged module.
>
> For Android and iOS modules, the module must be formatted as a CommonJS module. For Mobile Web, the module must use the Asynchronous Module Definition (AMD) format.
>
> You can place additional JavaScript CommonJS modules in the assets folder and import them into your main module using `require`.
>
> If your module includes both JavaScript and native code, the native and JavaScript module contents are merged when the module is packaged. For example, if your native module exposes a `createView` method, and you have a JavaScript module that exposes a `animateView` method, both of these methods are available on your module:
>
> ```js
> var myModule = require("com.example.module");
> var view = myModule.createView({ width: 200, height: 200 });
> win.add(view);
> myModule.animateView(view);
> ```
