### ISSUE TITLE
Compiling problem with 64bits module of TiCollectionView

### ISSUE THREAD

**Issue by kilyan-s** [mpociot/TiCollectionView#21]
I tried to compile the application on an iPhone 6 plus (with TiCollectionView 1.2.0 and my module compilation version is 3.5.0.GA of Titanium SDK), I got an error: 

(My application are compiled with 3.5.0.GA)

Thank you  
-------
"Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_TiSelectedCellBackgroundView", referenced from:
      objc-class-ref in libde.marcelpociot.collectionview.a(DeMarcelpociotCollectionviewCollectionItem.o)
  "_OBJC_CLASS_$_TiUIRefreshControlProxy", referenced from:
      objc-class-ref in libde.marcelpociot.collectionview.a(DeMarcelpociotCollectionviewCollectionView.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

**Comment by mpociot** [comment]
Hi,
Right now the Pull To Refresh dependency is hard coded. For an easy fix place this somewhere in your code:

```
Ti.UI.createRefreshControl({})
```

This forces Titanium to include the refresh control header files

**Comment by yuchi** [comment]
There's a constant to be used with `#IFDEF` if you want to make the code more solid on this side.

**Comment by yuchi** [comment]
[Here it is](https://github.com/smclab/TiSoftKeyboard/blob/870a990fabe77be319f23f63f2c52d86faaa1568/Classes/TiUIScrollViewProxy%2BKeyboardDismiss.m#L18) in one of our modules, and [here’s the actual code](https://github.com/appcelerator/titanium_mobile/blob/afc36d4f421424dc1ef6d618201f43616bb7857b/iphone/Classes/TiUITableView.h#L15) from @appcelerator.

**should** be:

```objective-c
#ifdef USE_TI_UIREFRESHCONTROL
// your safe code here
#endif
```

**Comment by yuchi** [comment]
Wait, you’re [already doing it](https://github.com/mpociot/TiCollectionView/blob/a8a520d9c5ae76b927566cfd4f25472a72814bc3/iphone/Classes/DeMarcelpociotCollectionviewCollectionView.m#L17).

Sorry…

**Comment by kilyan-s** [comment]
It worked for the pull to refresh error thank you but I still have the SelectedCellBackgroundView error. I added the property selectedBackgroundColor to each item in the collectionView but nothing changed.

----
"_OBJC_CLASS_$_TiSelectedCellBackgroundView", referenced from:"

**Comment by kilyan-s** [comment]
I can't figure out why I have this error, I tried to compile with an older version of Titanium's SDK but it doesn't work either. I can't run the app on a device, do you know why I have this error ?

**Comment by mpociot** [comment]
Sorry, still need to look into it. I'm not having an issue with this (on device and simulator)

**Comment by mpociot** [comment]
Okay - so I finally had the time to look into this issue.

The module uses the "TiSelectedCellbackgroundView" class from the base SDK. That class only gets included when you use a table- or listview somewhere in your app.
So as a hotfix, similar to the refresh control, add this somewhere in your code:

`Ti.UI.createTableView({})`

That should do the trick until a new version is out.
