### ISSUE TITLE
Error when building on iOs device

### ISSUE THREAD

**Issue by sebzincktiz** [mpociot/TiCollectionView#23]
Hello,
got the following error when building on iOs device (works on simulator).
Any idea ?

Thanks you

My config:
Iphone 5s
Titanium Command-Line Interface, CLI version 3.4.1, Titanium SDK version 3.5.0.GA

[ERROR] :  2015-02-12 18:19:22.845 xcodebuild[25380:709992] [MT] DVTAssertions: Warning in /SourceCache/IDEFrameworks/IDEFrameworks-6611/IDEFoundation/SourceControl/Model/IDESourceControlManager.m:423
[ERROR] :  Details:  Error Domain=com.apple.dt.IDESourceControlErrorDomain Code=-1 "Missing extension: public.vcs.subversion" UserInfo=0x7ff8c8806da0 {NSLocalizedDescription=Missing extension: public.vcs.subversion}
[ERROR] :  Object:   <IDESourceControlManager: 0x7ff8c8805930>
[ERROR] :  Method:   -loadRepositories
[ERROR] :  Thread:   <NSThread: 0x7ff8c1d2e270>{number = 1, name = main}
[ERROR] :  Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/RestoMalin.build/Debug-iphoneos/RestoMalin-universal.build/Objects-normal/armv7/RestoMalin normal armv7
[ERROR] :  	Ld build/RestoMalin.build/Debug-iphoneos/RestoMalin-universal.build/Objects-normal/arm64/RestoMalin normal arm64
[ERROR] :  (2 failures)

**Comment by mpociot** [comment]
To be honest, I don't think that this is related to my module.
Do you have a "loadRepositories" function somewhere in your code?

**Comment by sebzincktiz** [comment]
No I don't have any repositories. If I remove the module in Tiapp.xml it works.

**Comment by Scyns** [comment]
I'm experiencing the same issue.

**Comment by mpociot** [comment]
Could you add some example code?

**Comment by Scyns** [comment]
I don't seem to get the error anymore. Don't know what sorted it out.
