### ISSUE TITLE
Example app won't run on Simulator with Ti 3.5.1.GA

### ISSUE THREAD

**Issue by TheBrousse** [mpociot/TiCollectionView#27]
The very basic *classic* Titanium example app provided with the module will not run on the iOS Simulator (selected iPad Air running iOS 8.2). Right at startup, we are shown with the following Error message: **"Couldn't find module: CollectionView for architecture: x86_64"** (see screenshot enclosed)

I created a standalone test project that reproduces the issue, this should make it easier for you to reproduce. Just clone the project and run it, you will see the error.

> https://github.com/TheBrousse/collectiontester

![ios simulator screen shot 26 mar 2015 21 17 29](https://cloud.githubusercontent.com/assets/606912/6856105/eca82aa6-d3fd-11e4-94be-d7433574c919.png)

**Comment by mpociot** [comment]
Hey,

that's because you need to include the commonJS library from the `lib` folder.
I really need to clarify this and improve the example...

**Comment by TheBrousse** [comment]
That did the trick thank you.
I would have read more thoroughly the documentation.
