### ISSUE TITLE
Error on Android

### ISSUE THREAD

**Issue by SkipperJohn-whqjvaap** [mpociot/TiCollectionView#42]
2 errors one after another during runtime in android.

----------------------------------------------------------------------------------------------------
[ERROR] :  TiExceptionHandler: (main) [8266,22027] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,22027] - In CollectionView.js:54,7
[ERROR] :  TiExceptionHandler: (main) [0,22027] - Message: Uncaught TypeError: Object #<UI> has no method 'createRefreshControl'
[ERROR] :  TiExceptionHandler: (main) [1,22028] - Source: Ti.UI.createRefreshControl();
[ERROR] :  V8Exception: Exception occurred at CollectionView.js:54: Uncaught TypeError: Object #<UI> has no method 'createRefreshControl'

----------------------------------------------------------------------------------------------------

[ERROR] :  TiExceptionHandler: (main) [1305,29400] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,29400] - In alloy/controllers/index.js:227,46
[ERROR] :  TiExceptionHandler: (main) [0,29400] - Message: Uncaught TypeError: Object #<Object> has no method 'createCollectionView'
[ERROR] :  TiExceptionHandler: (main) [0,29400] - Source:     var listView = require("CollectionView").createCollectionView({
[ERROR] :  V8Exception: Exception occurred at alloy/controllers/zo.js:227: Uncaught TypeError: Object #<Object> has no method 'createCollectionView'

**Comment by nuno** [comment]
@SkipperJohn-whqjvaap What I did to solve that error was in app/lib/CollectionView.js put the ```Ti.UI.createRefreshControl();``` in the ios block, Fixed for me.

```
Ti.UI.createListView();
Ti.UI.createTableView();
if(OS_IOS){
	Ti.UI.createRefreshControl();
}
```

**Comment by SkipperJohn-whqjvaap** [comment]
why is headerView & footerView of list not showing up in ios?

**Comment by yuchi** [comment]
@SkipperJohn-whqjvaap probably related: #35
