### ISSUE TITLE
listView not showing (randomly, on initial creation) on 4.1.0.GA

### ISSUE THREAD

**Issue by skoften** [mpociot/TiCollectionView#43]
I have a listView with 2 columns for iPad users which worked fine, until I tried to build it with 4.1.0.GA.

The listView doesn't show up the first time. After a refresh, which removes the listView from his parent container, and re-adds it again, it seem to work fine again.

Logs:

[INFO] :   [object DeMarcelpociotCollectionviewModule] loaded
. here I am loading the remote JSON feed, creating and building up the listView with data
[INFO] :   configureHeaders called
[INFO] :   setHeaderFooter called
[INFO] :   frameSizeChanged
[INFO] :   frameSizeChanged:search !isActive

// log ends here, listView doesn't gets generated on screen

After a refresh, besides the log above, the following part is also showing:

[INFO] :   Section count: 1
[INFO] :   Item count: 16
[INFO] :   sizeForItemAtIndexPath
[INFO] :   Size: {326.79998779296875, 265}
etc..

**Comment by nuno** [comment]
@skoften Hey, is nothing to do with this cool module, is abug on ti sdk 4.1.GA, see for you self

[https://jira.appcelerator.org/browse/TIMOB-19209](https://jira.appcelerator.org/browse/TIMOB-19209)


I have this issue too.

**Comment by caspahouzer** [comment]
Nuno, can you please push the issue with a comment. It’s important to gain more user with this problem to get it fixed asap!

- Sebastian

**Comment by nuno** [comment]
@caspahouzer sorry?

**Comment by skoften** [comment]
@nuno, ah, that could be it. Although I currently have a fixed/static height on the item row.

Thanks for your reply!

**Comment by nuno** [comment]
@skoften   you can be close this issue?
