### ISSUE TITLE
Question add view between items

### ISSUE THREAD

**Issue by nuno** [mpociot/TiCollectionView#47]
I have a grid layout with 2 columns and 4 items (total 4), I added a custom view in the index 2, the question is, it is possible that the custom view can stay in the middle of the 4 columns but with full width?

Purpose: the custom view is to have a ADS in the middle.

******************************
Legend:

### = =

******************************
### __    1 - ads view

PS The question is more related the UI possible logic, the code for add the custom view is there already, but shows like a column and not a full with column like the goal.

**Comment by nuno** [comment]
related to the last comment I add this Image as reference: 

![](https://docs.google.com/uc?id=0B-QA9Zb260-1TWJvWDBpVDBxdWs)

thanks.

**Comment by chuck415** [comment]
For mobile, the goal image is good. For tablet, it's going to be more similar what you have know, but the ad is centered vertically with the cards in the row.

**Comment by nuno** [comment]
Solved by have 2 item templates.
