### ISSUE TITLE
Position of item clicked

### ISSUE THREAD

**Issue by RayKahn** [mpociot/TiCollectionView#49]
I am trying to create a Pinterest like effect using the CollectionView. How do I get the top and left values of an item when it is clicked? Is there a simpler way of getting an item's position?

**Comment by nuno** [comment]
@RayKahn You figure out?

**Comment by RayKahn** [comment]
Yes I did...

**Comment by nuno** [comment]
@RayKahn you want share with the ppl? :)

**Comment by RayKahn** [comment]
Sure... bcontainer is my main view:

function itemClicked(event) {
	
	var point = event.source.convertPointToView({
		x: event.x,
		y: event.y
	}, $.bcontainer);
	
	var offer 	= offersDataSet[event.itemIndex]; // this is my data array

	var left 	= point.x - event.x;
	var top 	= point.y - event.y;

}

**Comment by nuno** [comment]
@RayKahn Thanks for sharing, may help others! :+1:

**Comment by nuno** [comment]
Hey @RayKahn in your "Pinterest like effect using the TiCollectionView" did you implemented the swipe photos?  And you open new window when  "item when it is clicked" or another View/ListView? Im curious and doing similar effect on one project.

**Comment by RayKahn** [comment]
@nuno I am not doing the "swipe photos" effect. But I do open a new window which displays the details of the element, just like Pinterest app does.

**Comment by nuno** [comment]
@RayKahn Ok thanks is like im doing, so with your "convertPointToView"  when you close the window to back to  collectionview again you go the right spot, correct?

**Comment by RayKahn** [comment]
@nuno That's correct. Since I just hide the main view (waterfall view), and do not close it, I am guaranteed to be back to the same spot when I minimize the detail view.

**Comment by nuno** [comment]
@RayKahn, interesting, then the (waterfall view) and the (detail view) are in the same window, you do not open a new window just for detail? Is the (detail view) a regular Ti.UI.View?

Good is the "SCROLL_HORIZONTAL" be dynamic and not "read only"

**Comment by RayKahn** [comment]
@nuno  Yes the detail page is a "view" within the main window which also houses the waterfall view. And the detail view is a regular Ti.UI.View.

I am not sure what you mean by 'Good is the "SCROLL_HORIZONTAL" be dynamic and not "read only"'

**Comment by nuno** [comment]
@RayKahn, this module have the ability to SCROLL_HORIZONTAL or GridView (vertically scroll), but we not able to change it on the fly.

If we where able to change we could change from Gridview to HORIZONTAL, the our detailview could be swipe able too. Like Pinterest :)

Take a look at the docs: 

iOS specific configuration (Creation Only!)
scrollDirection (SCROLL_HORIZONTAL | SCROLL_VERTICAL ) Default: SCROLL_VERTICAL

**Comment by RayKahn** [comment]
@nuno OK I see what you mean. I only use vertical scroll.

**Comment by nuno** [comment]
@RayKahn, question, in your example:

```
function itemClicked(event) {

var point = event.source.convertPointToView({
    x: event.x,
    y: event.y
}, $.bcontainer);

var offer   = offersDataSet[event.itemIndex]; // this is my data array

var left    = point.x - event.x;
var top     = point.y - event.y;
}
```

```$.bcontaine``` is exactly what? I ask you becouse in my tests I get always errors:

```
[ERROR] :  Script Error {
[ERROR] :      column = 36;
[ERROR] :      line = 14;
[ERROR] :      nativeLocation = "-[TiViewProxy convertPointToView:] (TiViewProxy.m:665)";
[ERROR] :      nativeReason = "Parameter is not convertable to a TiPoint";
[ERROR] :  }

```

Thanks @RayKahn !

**Comment by RayKahn** [comment]
@nuno $bcontainer is the view which holds the waterfall view (module="de.marcelpociot.collectionview").  I have defined that in my index.xml. See below.

`<Alloy>`
	`<Window id="indexWin">`
		`<View id="bcontainer">`
`<ListView id="_listView" defaultItemTemplate="offers" module="de.marcelpociot.collectionview" method="createCollectionView"
			renderDirection="collectionView.DIRECTION_SHORTEST_FIRST" columnCount="2" layout="1" minimumColumnSpacing="2" minimumInteritemSpacing="2">`
				`<Templates>`
					`<ItemTemplate name="offers" class="_offers">`
						`<View class="mainView" layout="vertical" top="0" bindId="mainView" onClick="itemClicked">`
							`<ImageView class="img" bindId="pic"></ImageView>`
							`<View class="topView" bindId="_topView" id="topView">`
								`<View class="infoView">`
									`<Label class="infoClass" bindId="info"></Label>`
								`</View>`
								`<View class="priceView" id="_priceView">`
									`<Label class="priceClass" bindId="price"></Label>`
								`</View>`
							`</View>`
							`<View class="hLine"></View>`
							`<View class="lowerView" bindId="_lowerView">`
								`<View class="providerView">`
									`<Label class="providerName" bindId="es_info"></Label>`
								`</View>`
								`<View class="likeView">`
									`<View class="iconView">`
										`<ImageView class="imgIcon" bindId="likeIcon"></ImageView>`
									`</View>`
									`<Label class="likeCount" bindId="like_count"></Label>`
								`</View>`
							`</View>`
						`</View>`
					`</ItemTemplate>`
				`</Templates>`
			`</ListView>`

Hope this helps.

**Comment by nuno** [comment]
ah you assigned the ```onClick="itemClicked"``` inside of the template, and not on the ```<ListView  ...``` directly.
You could have told me initially,  had avoided so many questions on my part :)

Thanks @RayKahn for your time!

**Comment by RayKahn** [comment]
@nuno Initially I tried that path but it wouldn't work. That's why I had to assign it inside the template.

**Comment by nuno** [comment]
@RayKahn Thanks :+1:
