### ISSUE TITLE
Feature: Pull to Refresh

### ISSUE THREAD

**Issue by viezel** [mpociot/TiCollectionView#6]
https://github.com/vlasov/CCBottomRefreshControl

**Comment by viezel** [comment]
maybe implement it like this: 
http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.UI.ListView-property-pullView

    <PullView>
      <View height="50" backgroundColor="black">
        <Label>Pull To Refresh</Label>
      </View>
    </PullView>

**Comment by mpociot** [comment]
Added in PR #12 by @adesugbaa :+1:
